import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { compileProject, execute } from '../../src/compiler.mjs';
import { fileProject } from '../../src/project-files.mjs';
const mode=process.argv[2]??'pure';
if(!['pure','host'].includes(mode))throw new Error('usage: node examples/ownership-frames/run.mjs [pure|host]');
const project=fileProject(fileURLToPath(new URL(`./${mode}.tt`,import.meta.url)));
const c=compileProject(project.entry,project.read);
const host=new Map([['operations.tt::Step',()=>2n],['operations.tt::Axis',()=>1n]]);
const result=execute(c.wasm,{host});
assert.equal(result.value.values[0].values[0],0n);
assert.equal(result.value.values[1].values[0],10000n);
assert.equal(result.value.values[2],40030n);
assert.equal(result.metrics.owned_live_bytes,0);
assert.equal(result.metrics.owned_reserved_bytes,1008);
assert.equal(result.metrics.owned_reuses,9999);
assert.equal(result.metrics.host_calls,mode==='host'?40000:0);
console.log(result.output);
console.log(JSON.stringify(result.metrics));
